### PR TITLE
Single script

### PR DESCRIPTION
**Pull request by astefanutti**

### CODE REVIEW

**Comment by rhuss** [comment]
@astefanutti thanks ! By accident, I also worked on a unification while I was trying to optimize the tests (and had a boring train ride ;-). 

Let me bring both PRs (this and #47) together and take the best of both of them .... :)

**Comment by astefanutti** [comment]
@rhuss ah I've just seen that. Should have been more explicit that I was working on it...

That sounds good, there may be a couple of things in this PR that can be valuable, hopefully :)

**Comment by rhuss** [comment]
Merged #47

**Comment by rhuss** [comment]
btw, took over the way how you disabled exec (i used a background job for this but thats very likel less table).

I slimmed down the calc() method a bit as the format currently is always %d, so removed that parameter.

**Pull request closed without merging**
